apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
  namespace: spacepods
rules:
  - apiGroups:
    - ""
    resources:
      - pods
    verbs: ["get", "list", "delete"]
