apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spacepods-backend
  name: spacepods-backend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: spacepods-backend
  template:
    metadata:
      labels:
        app: spacepods-backend
    spec:
      serviceAccountName: api-service-account
      containers:
      - name: spacepods-backend
        image: registry.tino.sh/spacePods-backend
        resources:
          requests:
            memory: "50Mi"
            cpu: "30m"
          limits:
            memory: "64Mi"
            cpu: "100m"
